"""empty message

Revision ID: 3b41186b48f4
Revises: 6de2a8035f48
Create Date: 2019-07-18 13:48:07.416786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b41186b48f4'
down_revision = '6de2a8035f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Email', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('Passwort', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Passwort')
    op.drop_column('user', 'Email')
    # ### end Alembic commands ###
