"""empty message

Revision ID: 6de2a8035f48
Revises: 
Create Date: 2019-07-16 17:24:57.021239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de2a8035f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Frage', sa.String(length=80), nullable=False),
    sa.Column('Option_eins', sa.String(length=80), nullable=False),
    sa.Column('Option_zwei', sa.String(length=80), nullable=False),
    sa.Column('Option_drei', sa.String(length=80), nullable=False),
    sa.Column('Option_vier', sa.String(length=80), nullable=False),
    sa.Column('Antwort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('fragenRichtig', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
